### ISSUE TITLE
Partial variables are matched

### ISSUE THREAD

**Issue by gastrodon** [gastrodon/persim#7]
Consider the table
```yml
vars:
    foo: I'm only foo
    foobar: I'm foo but with bar
 
routes:
   ...
   description: I want $foobar
```

This may result in `I want I'm only foobar` because only `$foo` is matched from `$foobar`, and the rest of the word bar is treated as a string literal
